Missing empty get_background_music() for builds without sounds.
Add missing empty get_background_music() function used when build without sound supoort.

Without it build fails on final linking when sounds are not enabled:
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld:
  title.o: in function title_screen_run':
    /home/.../source/freedroid-src/src/title.c:255: undefined reference toget_background_music'
collect2: error: ld returned 1 exit status